// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/data-structures.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RearrangeArrayAlternately_Test_Case struct {
	Length               int64    `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Array                []int64  `protobuf:"varint,2,rep,packed,name=array,proto3" json:"array,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RearrangeArrayAlternately_Test_Case) Reset()         { *m = RearrangeArrayAlternately_Test_Case{} }
func (m *RearrangeArrayAlternately_Test_Case) String() string { return proto.CompactTextString(m) }
func (*RearrangeArrayAlternately_Test_Case) ProtoMessage()    {}
func (*RearrangeArrayAlternately_Test_Case) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3a9062788d88704, []int{0}
}

func (m *RearrangeArrayAlternately_Test_Case) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RearrangeArrayAlternately_Test_Case.Unmarshal(m, b)
}
func (m *RearrangeArrayAlternately_Test_Case) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RearrangeArrayAlternately_Test_Case.Marshal(b, m, deterministic)
}
func (m *RearrangeArrayAlternately_Test_Case) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RearrangeArrayAlternately_Test_Case.Merge(m, src)
}
func (m *RearrangeArrayAlternately_Test_Case) XXX_Size() int {
	return xxx_messageInfo_RearrangeArrayAlternately_Test_Case.Size(m)
}
func (m *RearrangeArrayAlternately_Test_Case) XXX_DiscardUnknown() {
	xxx_messageInfo_RearrangeArrayAlternately_Test_Case.DiscardUnknown(m)
}

var xxx_messageInfo_RearrangeArrayAlternately_Test_Case proto.InternalMessageInfo

func (m *RearrangeArrayAlternately_Test_Case) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *RearrangeArrayAlternately_Test_Case) GetArray() []int64 {
	if m != nil {
		return m.Array
	}
	return nil
}

type RearrangeArrayAlternatelyRequest struct {
	TestcasesCount       int64    `protobuf:"varint,1,opt,name=testcases_count,json=testcasesCount,proto3" json:"testcases_count,omitempty"`
	Array                []int64  `protobuf:"varint,2,rep,packed,name=Array,proto3" json:"Array,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RearrangeArrayAlternatelyRequest) Reset()         { *m = RearrangeArrayAlternatelyRequest{} }
func (m *RearrangeArrayAlternatelyRequest) String() string { return proto.CompactTextString(m) }
func (*RearrangeArrayAlternatelyRequest) ProtoMessage()    {}
func (*RearrangeArrayAlternatelyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3a9062788d88704, []int{1}
}

func (m *RearrangeArrayAlternatelyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RearrangeArrayAlternatelyRequest.Unmarshal(m, b)
}
func (m *RearrangeArrayAlternatelyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RearrangeArrayAlternatelyRequest.Marshal(b, m, deterministic)
}
func (m *RearrangeArrayAlternatelyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RearrangeArrayAlternatelyRequest.Merge(m, src)
}
func (m *RearrangeArrayAlternatelyRequest) XXX_Size() int {
	return xxx_messageInfo_RearrangeArrayAlternatelyRequest.Size(m)
}
func (m *RearrangeArrayAlternatelyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RearrangeArrayAlternatelyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RearrangeArrayAlternatelyRequest proto.InternalMessageInfo

func (m *RearrangeArrayAlternatelyRequest) GetTestcasesCount() int64 {
	if m != nil {
		return m.TestcasesCount
	}
	return 0
}

func (m *RearrangeArrayAlternatelyRequest) GetArray() []int64 {
	if m != nil {
		return m.Array
	}
	return nil
}

type RearrangeArrayAlternatelyResponse struct {
	Array                []int64  `protobuf:"varint,1,rep,packed,name=array,proto3" json:"array,omitempty"`
	ArrangedArray        []int64  `protobuf:"varint,2,rep,packed,name=arranged_array,json=arrangedArray,proto3" json:"arranged_array,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RearrangeArrayAlternatelyResponse) Reset()         { *m = RearrangeArrayAlternatelyResponse{} }
func (m *RearrangeArrayAlternatelyResponse) String() string { return proto.CompactTextString(m) }
func (*RearrangeArrayAlternatelyResponse) ProtoMessage()    {}
func (*RearrangeArrayAlternatelyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3a9062788d88704, []int{2}
}

func (m *RearrangeArrayAlternatelyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RearrangeArrayAlternatelyResponse.Unmarshal(m, b)
}
func (m *RearrangeArrayAlternatelyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RearrangeArrayAlternatelyResponse.Marshal(b, m, deterministic)
}
func (m *RearrangeArrayAlternatelyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RearrangeArrayAlternatelyResponse.Merge(m, src)
}
func (m *RearrangeArrayAlternatelyResponse) XXX_Size() int {
	return xxx_messageInfo_RearrangeArrayAlternatelyResponse.Size(m)
}
func (m *RearrangeArrayAlternatelyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RearrangeArrayAlternatelyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RearrangeArrayAlternatelyResponse proto.InternalMessageInfo

func (m *RearrangeArrayAlternatelyResponse) GetArray() []int64 {
	if m != nil {
		return m.Array
	}
	return nil
}

func (m *RearrangeArrayAlternatelyResponse) GetArrangedArray() []int64 {
	if m != nil {
		return m.ArrangedArray
	}
	return nil
}

func init() {
	proto.RegisterType((*RearrangeArrayAlternately_Test_Case)(nil), "proto.RearrangeArrayAlternately_Test_Case")
	proto.RegisterType((*RearrangeArrayAlternatelyRequest)(nil), "proto.RearrangeArrayAlternatelyRequest")
	proto.RegisterType((*RearrangeArrayAlternatelyResponse)(nil), "proto.RearrangeArrayAlternatelyResponse")
}

func init() { proto.RegisterFile("pkg/proto/data-structures.proto", fileDescriptor_e3a9062788d88704) }

var fileDescriptor_e3a9062788d88704 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xdd, 0x4a, 0x02, 0x41,
	0x14, 0x66, 0x14, 0xbd, 0x18, 0xc8, 0x60, 0x88, 0x30, 0x09, 0xb4, 0x8d, 0x50, 0x02, 0x1d, 0xb2,
	0x9b, 0xe8, 0x4e, 0xec, 0x09, 0xd6, 0xee, 0xb7, 0xa3, 0x9e, 0x36, 0x69, 0x9d, 0xd9, 0xe6, 0x9c,
	0x0d, 0xbc, 0xed, 0x15, 0x7a, 0x89, 0xde, 0xa1, 0xc7, 0xe8, 0x15, 0x7a, 0x90, 0x70, 0x76, 0x32,
	0x6f, 0xcc, 0xab, 0xe1, 0x7c, 0x7c, 0x7f, 0xe7, 0x30, 0xb2, 0x9d, 0x3f, 0xa7, 0x3a, 0x77, 0x96,
	0xad, 0x9e, 0x03, 0x43, 0x9f, 0xd8, 0x15, 0x33, 0x2e, 0x1c, 0xd2, 0xc0, 0xa3, 0xaa, 0xe6, 0x9f,
	0x56, 0x3b, 0xb5, 0x36, 0xcd, 0xb0, 0xa4, 0x4e, 0x8b, 0x47, 0xcd, 0x8b, 0x25, 0x12, 0xc3, 0x32,
	0x2f, 0x79, 0xad, 0xd3, 0x40, 0x80, 0x7c, 0xa1, 0xc1, 0x18, 0xcb, 0xc0, 0x0b, 0x6b, 0x82, 0x4b,
	0x34, 0x91, 0xe7, 0x31, 0x82, 0x73, 0x60, 0x52, 0x1c, 0x39, 0x07, 0xab, 0x51, 0xc6, 0xe8, 0x0c,
	0x30, 0x66, 0xab, 0xe4, 0x1e, 0x89, 0x93, 0x31, 0x10, 0xaa, 0x63, 0x59, 0xcf, 0xd0, 0xa4, 0xfc,
	0xd4, 0x14, 0x1d, 0xd1, 0xab, 0xc6, 0x61, 0x52, 0x47, 0xb2, 0xb6, 0x16, 0xaf, 0x9a, 0x95, 0x4e,
	0xb5, 0x57, 0x8d, 0xcb, 0x21, 0x02, 0xd9, 0xd9, 0x69, 0x1a, 0xe3, 0x4b, 0x81, 0xc4, 0xaa, 0x2b,
	0x0f, 0x19, 0x89, 0x67, 0x40, 0x48, 0xc9, 0xcc, 0x16, 0x86, 0x83, 0x75, 0x63, 0x03, 0x8f, 0xd7,
	0xe8, 0x3a, 0x62, 0xb4, 0x1d, 0xe1, 0x87, 0xe8, 0x41, 0x9e, 0xfd, 0x13, 0x41, 0xb9, 0x35, 0x84,
	0x7f, 0xed, 0xc4, 0x56, 0x3b, 0x75, 0x21, 0x1b, 0x41, 0x38, 0x4f, 0xb6, 0xcb, 0x1f, 0xfc, 0xa2,
	0xde, 0x6f, 0xf8, 0x29, 0x64, 0xe3, 0x0e, 0x18, 0x26, 0x9b, 0xc3, 0xab, 0x0f, 0x21, 0x4f, 0x76,
	0xa6, 0xaa, 0x6e, 0x79, 0xd2, 0xc1, 0xbe, 0xd5, 0x5b, 0xbd, 0xfd, 0xc4, 0x72, 0x81, 0xe8, 0xe6,
	0xed, 0xeb, 0xfb, 0xbd, 0x32, 0x8c, 0xfa, 0xfa, 0xf5, 0xca, 0x7f, 0x83, 0x84, 0x1c, 0x87, 0x36,
	0x7a, 0xa7, 0xfc, 0x56, 0x5c, 0x4e, 0xeb, 0x3e, 0xe2, 0xfa, 0x27, 0x00, 0x00, 0xff, 0xff, 0xff,
	0xa1, 0x04, 0x53, 0x47, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataStructuresClient is the client API for DataStructures service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataStructuresClient interface {
	RearrangeArrayAlternately(ctx context.Context, in *RearrangeArrayAlternatelyRequest, opts ...grpc.CallOption) (*RearrangeArrayAlternatelyResponse, error)
}

type dataStructuresClient struct {
	cc *grpc.ClientConn
}

func NewDataStructuresClient(cc *grpc.ClientConn) DataStructuresClient {
	return &dataStructuresClient{cc}
}

func (c *dataStructuresClient) RearrangeArrayAlternately(ctx context.Context, in *RearrangeArrayAlternatelyRequest, opts ...grpc.CallOption) (*RearrangeArrayAlternatelyResponse, error) {
	out := new(RearrangeArrayAlternatelyResponse)
	err := c.cc.Invoke(ctx, "/proto.DataStructures/RearrangeArrayAlternately", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataStructuresServer is the server API for DataStructures service.
type DataStructuresServer interface {
	RearrangeArrayAlternately(context.Context, *RearrangeArrayAlternatelyRequest) (*RearrangeArrayAlternatelyResponse, error)
}

// UnimplementedDataStructuresServer can be embedded to have forward compatible implementations.
type UnimplementedDataStructuresServer struct {
}

func (*UnimplementedDataStructuresServer) RearrangeArrayAlternately(ctx context.Context, req *RearrangeArrayAlternatelyRequest) (*RearrangeArrayAlternatelyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RearrangeArrayAlternately not implemented")
}

func RegisterDataStructuresServer(s *grpc.Server, srv DataStructuresServer) {
	s.RegisterService(&_DataStructures_serviceDesc, srv)
}

func _DataStructures_RearrangeArrayAlternately_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RearrangeArrayAlternatelyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStructuresServer).RearrangeArrayAlternately(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DataStructures/RearrangeArrayAlternately",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStructuresServer).RearrangeArrayAlternately(ctx, req.(*RearrangeArrayAlternatelyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataStructures_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DataStructures",
	HandlerType: (*DataStructuresServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RearrangeArrayAlternately",
			Handler:    _DataStructures_RearrangeArrayAlternately_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/data-structures.proto",
}
